package com.rackluxury.rollsroyce.activities.util;

import com.rackluxury.rollsroyce.activities.models.MediaObject;

public class Resources {

    public static final MediaObject[] MEDIA_OBJECTS = {
            new MediaObject("Rolls-Royce Exterion Concept\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F1.mp4?alt=media&token=c2f00390-2c8b-4fc7-9fe4-7f63d42db311",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F1.jpg?alt=media&token=a0c5af20-bedb-4c90-8a0d-343277854b5c",
                    "This is a showcase video from Rolls Royce."),

            new MediaObject("Rolls-Royce for Barbie from Abu Dhabi\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F2.mp4?alt=media&token=63468dcf-0179-48dc-aa1e-cd337de51bf9",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F2.jpg?alt=media&token=9b14684d-4067-44f9-9fe1-1fca88bbfa4c",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2019 Rolls Royce Cullinan by Cherry Red - royal purple\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F3.mp4?alt=media&token=8e859bfe-9363-4542-81c6-e1e3d8044dae",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F3.jpg?alt=media&token=a0de1def-c644-4703-8be3-81de13a9488a",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("Mansory Rolls-Royce Cullinan Billionaire for millionaires\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F4.mp4?alt=media&token=2c25ad19-7578-4c35-bcb8-e584f3ad1261",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F4.jpg?alt=media&token=1c0206db-74bd-4dc8-a241-f1b51c1fb037",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2019 Rolls-Royce Phantom EWB with Privacy Suite\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F5.mp4?alt=media&token=2979087c-e494-4d90-a0cb-d2691bb137aa",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F5.jpg?alt=media&token=38d87c99-0de1-4512-b20d-1fcc24ac1b18",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2020 Rolls-Royce Cullinan Black Badge V12 sinister new look\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F6.mp4?alt=media&token=999efe14-863b-4566-9d06-0b678e70ae48",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F6.jpg?alt=media&token=c0292973-df6e-4107-bf4f-beada39c81be",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("Rolls-Royce Red Phantom - the 115th Anniversary of luxury\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F7.mp4?alt=media&token=2d4f951f-1aef-4588-9bfa-2edcfeaf20e2",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F7.jpg?alt=media&token=49bd0194-d2cd-494c-b1f6-52113cb0236a",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("Rolls-Royce Phantom Spofec - improved perfection\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F8.mp4?alt=media&token=e1a60b32-644a-4eca-881d-2160ac6ca0fe",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F8.jpg?alt=media&token=842cdcc2-372b-4d54-9078-e6f47a15e738",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2019 Rolls-Royce Onyx Concept Wraith black star\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F9.mp4?alt=media&token=c33335ef-1ea9-4555-8a9f-1f56178af6b0",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F9.jpg?alt=media&token=e058472b-74ac-46b7-be2d-e7efeb18ec56",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2019 Rolls-Royce Wraith by Prior Design - discreet styling\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F10.mp4?alt=media&token=d6db1b13-233a-494e-8928-0c39a05317bb",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F10.jpg?alt=media&token=cbb7ad5f-2f34-4da4-aebd-21cfe261b03e",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2008 Rolls-Royce Phantom Drophead Coupé big like the sun\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F11.mp4?alt=media&token=8bc75f9a-5962-41df-a84f-bcc6ff2e64ad",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F11.jpg?alt=media&token=5debe384-db0c-4bb7-8890-bf0a5a07a9f5",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2021 Mansory’s Rolls-Royce Cullinan Coastline ultimate luxury\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F12.mp4?alt=media&token=5f57d34f-94ce-45b8-9ee2-9a59a70dcd8c",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F12.jpg?alt=media&token=6e850cd8-9bc2-4aac-8049-2653459b3c9a",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("2020 Rolls-Royce Cullinan wide body kit by Mansory\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F13.mp4?alt=media&token=1a3ebeed-965d-4176-9cff-3c0b60118cb9",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F13.jpg?alt=media&token=24cc024a-daee-43fd-a27e-7af205513bb1",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("1997 Rolls-Royce Silver Spur classic luxury saloon\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F14.mp4?alt=media&token=d4e7643e-2b5c-4cbe-8f70-3a28c2941384",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F14.jpg?alt=media&token=81b31f34-a0fc-481e-9517-adc94ebda938",
                    "This is a showcase video from Rolls Royce."),
            new MediaObject("British Racing Green Rolls-Royce Cullinan from Mansory\n",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2F15.mp4?alt=media&token=6b6229d4-dad7-436c-ac98-60f96575054e",
                    "https://firebasestorage.googleapis.com/v0/b/rolls-royce-cars.appspot.com/o/Videos%2FThumbnails%2F15.jpg?alt=media&token=8abe10a8-0e69-472f-9e68-998e8b5b1a49",
                    "This is a showcase video from Rolls Royce."),



    };
}